### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by kbingham** [Jiangshan00001/pylibcamera#1]
Hello.

Thanks for starting some framework for python with libcamera. What are your plans with this project?
It will conflict with the namespace of our plans for formal upstream components.

We have now finished merging the main python bindings in libcamera, and we expect in the future to have a 'pylibcamera' component to expose a pythonic interface to that.

**Comment by Jiangshan00001** [comment]
@kbingham hi,
this project is just for my one raspberrypi project.
if you have some other good libcamera binding that can work better, i can release the pypi pylibcamera for sure.
but it may take me some time, as my project is already released to some clients. i have to upgrade their system.
as soon as i have done it, i will tell u and release the namespace, maybe 1-week to 1-month.

**Comment by kbingham** [comment]
I don't think there's any rush, but in regards to other bindings, have you seen the picamera2 work that is available from raspberry pi? That sits on top of our internal bindings, and is likely easier for you to use directly.

**Comment by Jiangshan00001** [comment]
@kbingham u could try to upload your code to pypi.

**Comment by kbingham** [comment]
Thank you
